[2024-11-22T08:07:24.734+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T08:07:24.741+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_stock_prediction.combine_predictions manual__2024-11-22T08:07:08.521728+00:00 [queued]>
[2024-11-22T08:07:24.744+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_stock_prediction.combine_predictions manual__2024-11-22T08:07:08.521728+00:00 [queued]>
[2024-11-22T08:07:24.744+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T08:07:24.749+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): combine_predictions> on 2024-11-22 08:07:08.521728+00:00
[2024-11-22T08:07:24.753+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13989) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T08:07:24.754+0000] {standard_task_runner.py:72} INFO - Started process 14000 to run task
[2024-11-22T08:07:24.755+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_stock_prediction', 'combine_predictions', 'manual__2024-11-22T08:07:08.521728+00:00', '--job-id', '1118', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdp1u8lrp']
[2024-11-22T08:07:24.755+0000] {standard_task_runner.py:105} INFO - Job 1118: Subtask combine_predictions
[2024-11-22T08:07:24.774+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_stock_prediction.combine_predictions manual__2024-11-22T08:07:08.521728+00:00 [running]> on host cba1e82f0ade
[2024-11-22T08:07:24.801+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_stock_prediction' AIRFLOW_CTX_TASK_ID='combine_predictions' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T08:07:08.521728+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T08:07:08.521728+00:00'
[2024-11-22T08:07:24.801+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T08:07:24.802+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T08:07:24.802+0000] {logging_mixin.py:190} INFO - Current task name:combine_predictions state:running start_date:2024-11-22 08:07:24.741475+00:00
[2024-11-22T08:07:24.802+0000] {logging_mixin.py:190} INFO - Dag name:weather_stock_prediction and current dag run status:running
[2024-11-22T08:07:24.802+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T08:07:24.808+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 313, in combine_predictions
    weather_forecast["price"] = predictions
    ~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'str' object does not support item assignment
[2024-11-22T08:07:24.813+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T08:07:24.813+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 08:07:24.741475+00:00 end:2024-11-22 08:07:24.813173+00:00 duration:0.071698
[2024-11-22T08:07:24.813+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): combine_predictions> dag:<DAG: weather_stock_prediction> dagrun:<DagRun weather_stock_prediction @ 2024-11-22 08:07:08.521728+00:00: manual__2024-11-22T08:07:08.521728+00:00, state:running, queued_at: 2024-11-22 08:07:08.527868+00:00. externally triggered: True>
[2024-11-22T08:07:24.813+0000] {logging_mixin.py:190} INFO - Failure caused by 'str' object does not support item assignment
[2024-11-22T08:07:24.814+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_stock_prediction, task_id=combine_predictions, run_id=manual__2024-11-22T08:07:08.521728+00:00, execution_date=20241122T080708, start_date=20241122T080724, end_date=20241122T080724
[2024-11-22T08:07:24.818+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T08:07:24.818+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1118 for task combine_predictions ('str' object does not support item assignment; 14000)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 313, in combine_predictions
    weather_forecast["price"] = predictions
    ~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'str' object does not support item assignment
[2024-11-22T08:07:24.855+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T08:07:24.863+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T08:07:24.864+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
