[2024-11-22T07:34:04.899+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T07:34:04.906+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_stock_prediction.combine_predictions manual__2024-11-22T07:23:47.897522+00:00 [queued]>
[2024-11-22T07:34:04.909+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_stock_prediction.combine_predictions manual__2024-11-22T07:23:47.897522+00:00 [queued]>
[2024-11-22T07:34:04.909+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-22T07:34:04.913+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): combine_predictions> on 2024-11-22 07:23:47.897522+00:00
[2024-11-22T07:34:04.919+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=11014) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T07:34:04.920+0000] {standard_task_runner.py:72} INFO - Started process 11025 to run task
[2024-11-22T07:34:04.920+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_stock_prediction', 'combine_predictions', 'manual__2024-11-22T07:23:47.897522+00:00', '--job-id', '933', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpyaqz7vz3']
[2024-11-22T07:34:04.921+0000] {standard_task_runner.py:105} INFO - Job 933: Subtask combine_predictions
[2024-11-22T07:34:04.946+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_stock_prediction.combine_predictions manual__2024-11-22T07:23:47.897522+00:00 [running]> on host cba1e82f0ade
[2024-11-22T07:34:04.980+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_stock_prediction' AIRFLOW_CTX_TASK_ID='combine_predictions' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T07:23:47.897522+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T07:23:47.897522+00:00'
[2024-11-22T07:34:04.981+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T07:34:04.981+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T07:34:04.982+0000] {logging_mixin.py:190} INFO - Current task name:combine_predictions state:running start_date:2024-11-22 07:34:04.906483+00:00
[2024-11-22T07:34:04.982+0000] {logging_mixin.py:190} INFO - Dag name:weather_stock_prediction and current dag run status:running
[2024-11-22T07:34:04.982+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T07:34:04.988+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 308, in combine_predictions
    weather_forecast["price"] = predictions
    ~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'str' object does not support item assignment
[2024-11-22T07:34:04.992+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T07:34:04.993+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 07:34:04.906483+00:00 end:2024-11-22 07:34:04.992622+00:00 duration:0.086139
[2024-11-22T07:34:04.993+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): combine_predictions> dag:<DAG: weather_stock_prediction> dagrun:<DagRun weather_stock_prediction @ 2024-11-22 07:23:47.897522+00:00: manual__2024-11-22T07:23:47.897522+00:00, state:running, queued_at: 2024-11-22 07:23:47.905753+00:00. externally triggered: True>
[2024-11-22T07:34:04.993+0000] {logging_mixin.py:190} INFO - Failure caused by 'str' object does not support item assignment
[2024-11-22T07:34:04.993+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=weather_stock_prediction, task_id=combine_predictions, run_id=manual__2024-11-22T07:23:47.897522+00:00, execution_date=20241122T072347, start_date=20241122T073404, end_date=20241122T073404
[2024-11-22T07:34:04.997+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T07:34:04.997+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 933 for task combine_predictions ('str' object does not support item assignment; 11025)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 308, in combine_predictions
    weather_forecast["price"] = predictions
    ~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'str' object does not support item assignment
[2024-11-22T07:34:05.029+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T07:34:05.038+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T07:34:05.039+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
