[2024-11-22T08:01:54.214+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T08:01:54.222+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_stock_prediction.load_data_postgres manual__2024-11-22T08:01:44.283658+00:00 [queued]>
[2024-11-22T08:01:54.228+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_stock_prediction.load_data_postgres manual__2024-11-22T08:01:44.283658+00:00 [queued]>
[2024-11-22T08:01:54.228+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T08:01:54.236+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data_postgres> on 2024-11-22 08:01:44.283658+00:00
[2024-11-22T08:01:54.244+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13474) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T08:01:54.245+0000] {standard_task_runner.py:72} INFO - Started process 13496 to run task
[2024-11-22T08:01:54.246+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_stock_prediction', 'load_data_postgres', 'manual__2024-11-22T08:01:44.283658+00:00', '--job-id', '1086', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp97icgat5']
[2024-11-22T08:01:54.247+0000] {standard_task_runner.py:105} INFO - Job 1086: Subtask load_data_postgres
[2024-11-22T08:01:54.282+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_stock_prediction.load_data_postgres manual__2024-11-22T08:01:44.283658+00:00 [running]> on host cba1e82f0ade
[2024-11-22T08:01:54.374+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_stock_prediction' AIRFLOW_CTX_TASK_ID='load_data_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T08:01:44.283658+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T08:01:44.283658+00:00'
[2024-11-22T08:01:54.377+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T08:01:54.377+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T08:01:54.378+0000] {logging_mixin.py:190} INFO - Current task name:load_data_postgres state:running start_date:2024-11-22 08:01:54.223555+00:00
[2024-11-22T08:01:54.378+0000] {logging_mixin.py:190} INFO - Dag name:weather_stock_prediction and current dag run status:running
[2024-11-22T08:01:54.378+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T08:01:54.390+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 325, in load_data_postgres
    for _, row in combined_data.iterrows():
                  ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'iterrows'
[2024-11-22T08:01:54.427+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T08:01:54.428+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 08:01:54.223555+00:00 end:2024-11-22 08:01:54.426735+00:00 duration:0.20318
[2024-11-22T08:01:54.428+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data_postgres> dag:<DAG: weather_stock_prediction> dagrun:<DagRun weather_stock_prediction @ 2024-11-22 08:01:44.283658+00:00: manual__2024-11-22T08:01:44.283658+00:00, state:running, queued_at: 2024-11-22 08:01:44.289193+00:00. externally triggered: True>
[2024-11-22T08:01:54.429+0000] {logging_mixin.py:190} INFO - Failure caused by 'str' object has no attribute 'iterrows'
[2024-11-22T08:01:54.429+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_stock_prediction, task_id=load_data_postgres, run_id=manual__2024-11-22T08:01:44.283658+00:00, execution_date=20241122T080144, start_date=20241122T080154, end_date=20241122T080154
[2024-11-22T08:01:54.440+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T08:01:54.440+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1086 for task load_data_postgres ('str' object has no attribute 'iterrows'; 13496)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 325, in load_data_postgres
    for _, row in combined_data.iterrows():
                  ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'iterrows'
[2024-11-22T08:01:54.468+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T08:01:54.479+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T08:01:54.479+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
