[2024-11-22T08:01:58.136+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T08:01:58.146+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_stock_prediction.predict_prices manual__2024-11-22T08:01:44.283658+00:00 [queued]>
[2024-11-22T08:01:58.151+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_stock_prediction.predict_prices manual__2024-11-22T08:01:44.283658+00:00 [queued]>
[2024-11-22T08:01:58.152+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T08:01:58.159+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): predict_prices> on 2024-11-22 08:01:44.283658+00:00
[2024-11-22T08:01:58.165+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13523) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T08:01:58.167+0000] {standard_task_runner.py:72} INFO - Started process 13534 to run task
[2024-11-22T08:01:58.167+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_stock_prediction', 'predict_prices', 'manual__2024-11-22T08:01:44.283658+00:00', '--job-id', '1089', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpfga5oo1k']
[2024-11-22T08:01:58.168+0000] {standard_task_runner.py:105} INFO - Job 1089: Subtask predict_prices
[2024-11-22T08:01:58.199+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_stock_prediction.predict_prices manual__2024-11-22T08:01:44.283658+00:00 [running]> on host cba1e82f0ade
[2024-11-22T08:01:58.227+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_stock_prediction' AIRFLOW_CTX_TASK_ID='predict_prices' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T08:01:44.283658+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T08:01:44.283658+00:00'
[2024-11-22T08:01:58.228+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T08:01:58.228+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T08:01:58.228+0000] {logging_mixin.py:190} INFO - Current task name:predict_prices state:running start_date:2024-11-22 08:01:58.147205+00:00
[2024-11-22T08:01:58.228+0000] {logging_mixin.py:190} INFO - Dag name:weather_stock_prediction and current dag run status:running
[2024-11-22T08:01:58.228+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T08:01:58.232+0000] {logging_mixin.py:190} INFO - Weather forecast data: {'date': {'0': '2024-11-22', '1': '2024-11-23', '2': '2024-11-24', '3': '2024-11-25', '4': '2024-11-26', '5': '2024-11-27', '6': '2024-11-28', '7': '2024-11-29', '8': '2024-11-30', '9': '2024-12-01', '10': '2024-12-02', '11': '2024-12-03', '12': '2024-12-04', '13': '2024-12-05', '14': '2024-12-06', '15': '2024-12-07'}, 'temperature': {'0': 14.94, '1': 13.3, '2': 12.75, '3': 12.84, '4': 12.23, '5': 11.72, '6': 10.73, '7': 10.74, '8': 11.19, '9': 11.87, '10': 11.96, '11': 12.07, '12': 15.04, '13': 15.66, '14': 15.9, '15': 16.04}, 'min_temperature': {'0': 12.33, '1': 11.05, '2': 10.15, '3': 11.19, '4': 11.52, '5': 10.1, '6': 9.12, '7': 8.87, '8': 9.07, '9': 9.72, '10': 10.39, '11': 10.02, '12': 10.47, '13': 11.17, '14': 11.47, '15': 12.17}, 'max_temperature': {'0': 15.91, '1': 13.41, '2': 13.37, '3': 14.17, '4': 13.06, '5': 13.46, '6': 13.75, '7': 14.05, '8': 14.47, '9': 14.95, '10': 14.52, '11': 15.0, '12': 15.55, '13': 15.66, '14': 16.08, '15': 16.14}, 'humidity': {'0': 85, '1': 74, '2': 61, '3': 69, '4': 83, '5': 57, '6': 58, '7': 57, '8': 57, '9': 55, '10': 54, '11': 54, '12': 47, '13': 45, '14': 49, '15': 57}, 'wind_speed': {'0': 9.04, '1': 4.91, '2': 6.3, '3': 6.67, '4': 4.29, '5': 3.82, '6': 3.96, '7': 3.99, '8': 4.05, '9': 4.15, '10': 3.48, '11': 3.66, '12': 3.74, '13': 3.19, '14': 2.99, '15': 3.36}}
[2024-11-22T08:01:58.239+0000] {logging_mixin.py:190} INFO -                                          temperature  ...                                         wind_speed
0  {'0': 14.94, '1': 13.3, '2': 12.75, '3': 12.84...  ...  {'0': 9.04, '1': 4.91, '2': 6.3, '3': 6.67, '4...

[1 rows x 5 columns]
[2024-11-22T08:01:58.240+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "lib.pyx", line 2374, in pandas._libs.lib.maybe_convert_numeric
TypeError: Invalid object type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 287, in predict_prices
    df = df.apply(pd.to_numeric)  # Coerce non-numeric to NaN
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10034, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 837, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 965, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/numeric.py", line 222, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]  # noqa: E501
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2416, in pandas._libs.lib.maybe_convert_numeric
TypeError: Invalid object type at position 0
[2024-11-22T08:01:58.246+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T08:01:58.246+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 08:01:58.147205+00:00 end:2024-11-22 08:01:58.246067+00:00 duration:0.098862
[2024-11-22T08:01:58.246+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): predict_prices> dag:<DAG: weather_stock_prediction> dagrun:<DagRun weather_stock_prediction @ 2024-11-22 08:01:44.283658+00:00: manual__2024-11-22T08:01:44.283658+00:00, state:running, queued_at: 2024-11-22 08:01:44.289193+00:00. externally triggered: True>
[2024-11-22T08:01:58.246+0000] {logging_mixin.py:190} INFO - Failure caused by Invalid object type at position 0
[2024-11-22T08:01:58.246+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_stock_prediction, task_id=predict_prices, run_id=manual__2024-11-22T08:01:44.283658+00:00, execution_date=20241122T080144, start_date=20241122T080158, end_date=20241122T080158
[2024-11-22T08:01:58.251+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T08:01:58.251+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1089 for task predict_prices (Invalid object type at position 0; 13534)
Traceback (most recent call last):
  File "lib.pyx", line 2374, in pandas._libs.lib.maybe_convert_numeric
TypeError: Invalid object type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 287, in predict_prices
    df = df.apply(pd.to_numeric)  # Coerce non-numeric to NaN
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10034, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 837, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 965, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/tools/numeric.py", line 222, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]  # noqa: E501
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2416, in pandas._libs.lib.maybe_convert_numeric
TypeError: Invalid object type at position 0
[2024-11-22T08:01:58.266+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T08:01:58.274+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T08:01:58.275+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
