[2024-11-22T06:09:48.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T06:09:48.436+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_stock_prediction.add_data manual__2024-11-22T06:04:39.565298+00:00 [queued]>
[2024-11-22T06:09:48.441+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_stock_prediction.add_data manual__2024-11-22T06:04:39.565298+00:00 [queued]>
[2024-11-22T06:09:48.441+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T06:09:48.445+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): add_data> on 2024-11-22 06:04:39.565298+00:00
[2024-11-22T06:09:48.450+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3504) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T06:09:48.450+0000] {standard_task_runner.py:72} INFO - Started process 3527 to run task
[2024-11-22T06:09:48.451+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_stock_prediction', 'add_data', 'manual__2024-11-22T06:04:39.565298+00:00', '--job-id', '503', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsxbiss45']
[2024-11-22T06:09:48.451+0000] {standard_task_runner.py:105} INFO - Job 503: Subtask add_data
[2024-11-22T06:09:48.470+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_stock_prediction.add_data manual__2024-11-22T06:04:39.565298+00:00 [running]> on host cba1e82f0ade
[2024-11-22T06:09:48.496+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_stock_prediction' AIRFLOW_CTX_TASK_ID='add_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T06:04:39.565298+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T06:04:39.565298+00:00'
[2024-11-22T06:09:48.497+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T06:09:48.497+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T06:09:48.497+0000] {logging_mixin.py:190} INFO - Current task name:add_data state:running start_date:2024-11-22 06:09:48.437019+00:00
[2024-11-22T06:09:48.497+0000] {logging_mixin.py:190} INFO - Dag name:weather_stock_prediction and current dag run status:running
[2024-11-22T06:09:48.497+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T06:09:48.503+0000] {logging_mixin.py:190} INFO - Data type of 'data': <class 'str'>
[2024-11-22T06:09:48.504+0000] {logging_mixin.py:190} INFO - Data type of 'postgres_data': <class 'str'>
[2024-11-22T06:09:48.504+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 201, in add_data
    raise TypeError("Both data and postgres_data must be DataFrames.")
TypeError: Both data and postgres_data must be DataFrames.
[2024-11-22T06:09:48.508+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T06:09:48.508+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 06:09:48.437019+00:00 end:2024-11-22 06:09:48.508505+00:00 duration:0.071486
[2024-11-22T06:09:48.508+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): add_data> dag:<DAG: weather_stock_prediction> dagrun:<DagRun weather_stock_prediction @ 2024-11-22 06:04:39.565298+00:00: manual__2024-11-22T06:04:39.565298+00:00, state:running, queued_at: 2024-11-22 06:04:39.574516+00:00. externally triggered: True>
[2024-11-22T06:09:48.509+0000] {logging_mixin.py:190} INFO - Failure caused by Both data and postgres_data must be DataFrames.
[2024-11-22T06:09:48.509+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_stock_prediction, task_id=add_data, run_id=manual__2024-11-22T06:04:39.565298+00:00, execution_date=20241122T060439, start_date=20241122T060948, end_date=20241122T060948
[2024-11-22T06:09:48.514+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T06:09:48.514+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 503 for task add_data (Both data and postgres_data must be DataFrames.; 3527)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 201, in add_data
    raise TypeError("Both data and postgres_data must be DataFrames.")
TypeError: Both data and postgres_data must be DataFrames.
[2024-11-22T06:09:48.550+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T06:09:48.559+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T06:09:48.559+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
