[2024-11-22T07:21:00.942+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T07:21:00.948+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_stock_prediction.predict_prices manual__2024-11-22T07:15:47.700843+00:00 [queued]>
[2024-11-22T07:21:00.951+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_stock_prediction.predict_prices manual__2024-11-22T07:15:47.700843+00:00 [queued]>
[2024-11-22T07:21:00.951+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-22T07:21:00.954+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): predict_prices> on 2024-11-22 07:15:47.700843+00:00
[2024-11-22T07:21:00.959+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=9649) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T07:21:00.959+0000] {standard_task_runner.py:72} INFO - Started process 9660 to run task
[2024-11-22T07:21:00.960+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_stock_prediction', 'predict_prices', 'manual__2024-11-22T07:15:47.700843+00:00', '--job-id', '846', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpi6bwh501']
[2024-11-22T07:21:00.960+0000] {standard_task_runner.py:105} INFO - Job 846: Subtask predict_prices
[2024-11-22T07:21:00.978+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_stock_prediction.predict_prices manual__2024-11-22T07:15:47.700843+00:00 [running]> on host cba1e82f0ade
[2024-11-22T07:21:01.003+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_stock_prediction' AIRFLOW_CTX_TASK_ID='predict_prices' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T07:15:47.700843+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T07:15:47.700843+00:00'
[2024-11-22T07:21:01.004+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T07:21:01.004+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T07:21:01.004+0000] {logging_mixin.py:190} INFO - Current task name:predict_prices state:running start_date:2024-11-22 07:21:00.948551+00:00
[2024-11-22T07:21:01.004+0000] {logging_mixin.py:190} INFO - Dag name:weather_stock_prediction and current dag run status:running
[2024-11-22T07:21:01.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T07:21:01.008+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 277, in predict_prices
    predictions = predictor.predict(weather_forecast)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/programs/model.py", line 21, in predict
    X_new = weather_data[["temperature", "min_temperature", "max_temperature", "humidity", "wind_speed"]]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
[2024-11-22T07:21:01.011+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-22T07:21:01.011+0000] {logging_mixin.py:190} INFO - Task start:2024-11-22 07:21:00.948551+00:00 end:2024-11-22 07:21:01.011534+00:00 duration:0.062983
[2024-11-22T07:21:01.011+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): predict_prices> dag:<DAG: weather_stock_prediction> dagrun:<DagRun weather_stock_prediction @ 2024-11-22 07:15:47.700843+00:00: manual__2024-11-22T07:15:47.700843+00:00, state:running, queued_at: 2024-11-22 07:15:47.710395+00:00. externally triggered: True>
[2024-11-22T07:21:01.012+0000] {logging_mixin.py:190} INFO - Failure caused by unhashable type: 'list'
[2024-11-22T07:21:01.012+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=weather_stock_prediction, task_id=predict_prices, run_id=manual__2024-11-22T07:15:47.700843+00:00, execution_date=20241122T071547, start_date=20241122T072100, end_date=20241122T072101
[2024-11-22T07:21:01.015+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T07:21:01.016+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 846 for task predict_prices (unhashable type: 'list'; 9660)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 277, in predict_prices
    predictions = predictor.predict(weather_forecast)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/programs/model.py", line 21, in predict
    X_new = weather_data[["temperature", "min_temperature", "max_temperature", "humidity", "wind_speed"]]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
[2024-11-22T07:21:01.021+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T07:21:01.030+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T07:21:01.031+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
